### ISSUE TITLE
Once downloaded

### ISSUE THREAD

**Issue by HedgeShot** [jadchaar/sec-edgar-downloader#1]
Hi Jad!

Thanks for the tool!
Do you have any recommendation on a way/tool to parse the TXT file that is downloaded (e.g. 13F)? My end goal is to get the X largest positions in a given 13F.

This is working but I need to manually get rid of some part of the TXT file downloaded [parse_13F](https://github.com/Hodapp87/parse_13F)

**Comment by jadchaar** [comment]
Hey @HedgeShot, apologies for the delayed reply--I have been trying to better understand how to parse the data properly myself for unit testing purposes. Sadly, SEC Edgar is quite dated and does not provide a good parse-friendly format like JSON or even a full submission in XML format.

If we take [Vanguard Group](https://www.sec.gov/Archives/edgar/data/102909/000095012319001986/0000950123-19-001986-index.htm), for example, the only way to retrieve the complete submission is through text format (as a text file) as the XML files listed only give a small bit of information. I primarily made this tool with the sole intention of downloading the filings in their raw text format and keeping the parsing up to the user.

That said, I'd love to help you out. Which portions of the file are you looking to extract information from? Which parts do you have to manually get rid of to use that tool?

Let me know. Thanks!

**Comment by HedgeShot** [comment]
Thanks for your answer.

I played a bit more with your tool and I am now able to parse 13F (haven't tried for any other filing) using the tool I mentioned above (parse_13F). I linked the two tools by creating a "pre-processing" function that basically create a XML file that fits the second tool from the downloaded TXT file.

By the way, did you get blacklisted from SEC after downloading many filings in a short time or they don't care? I took around 1500 filings without problem but just wondering.

**Comment by jadchaar** [comment]
I did remember reading somewhere in the past about how it is possible for your IP to get blacklisted if you search too quickly, but I am yet to encounter it myself.

Also, I am curious, are you extracting the XML portion that contains the information table from the 13-F?

**Comment by HedgeShot** [comment]
yes I am creating a new XML file with everything between the 2nd <XML> tag as this is the information about holdings that I need and then parse it with the tool linked above. It works for recent filings so it is enough for me but I imagine it will be a pain to make it compatible with older filings. I already encountered 3-4 slightly different XML formed documents...

**Comment by jadchaar** [comment]
Yeah that is a huge issue with SEC Edgar--there is no standardization at all. If the SEC standardized the XML format for all filings, it would be great. Hopefully in the future things improve.

**Comment by jadchaar** [comment]
Also @HedgeShot I just noticed that SEC Edgar offers the raw info tables in XML format on the website. For example, the latest 13F for Vanguard: https://www.sec.gov/Archives/edgar/data/102909/000095012319001986/0000950123-19-001986-index.htm.

I bet these are just inserted into the txt file I obtain in this package as is, but it may be worth a try to see if the standalone files are more standardized.

**Comment by HedgeShot** [comment]
indeed! At first I thought you were stitching together 3 files, header/1st xml/2nd xml, to create your TXT as I have never clicked on this "Complete submission text" file. It can probably help to download the XML file directly but not by much, I guess. Eventually, the full submission file is fine for me. 

Thanks again for your tool!

**Comment by jadchaar** [comment]
Hah! I wish the data was friendlier, but sadly this is the big chunk of data we are given :(.

Thanks for using the tool and reaching out!
