### ISSUE TITLE
HTTPError: 500 Internal Server Error

### ISSUE THREAD

**Issue by alexdinisor98** [jadchaar/sec-edgar-downloader#103]
Hello Jad,

I encountered this issue, when trying to run the .get function for 10-K filings, searching by CIK, in a loop with 7k steps, as follows: After the 10-15th iteration it throws this error "HTTPError: 500 Server Error: Internal Server Error for url: https://efts.sec.gov/LATEST/search-index". 
Is there a way to address this issue? I even tried with a time.sleep() of 10 seconds, but it leads to the same error.

Thanks in advance,
Alexandra

**Comment by JJery-web** [comment]
Yes I also meet the same question.

**Comment by georgegee23** [comment]
Hi Jad, was a solution found for this? I am currently getting the same error.

**Comment by georgegee23** [comment]
Hi Jad, was a solution for this issue found? I am currently getting the same error.

**Comment by jadchaar** [comment]
Hi folks is this issue still being seen on the latest version of the package? Please re-open this issue if it is still re-occurring.
