### ISSUE TITLE
Incomplete data age

### ISSUE THREAD

**Issue by JJery-web** [jadchaar/sec-edgar-downloader#104]
Hello, I found that some files (I downloaded 10Ks) have incomplete years. For example, only the data from 2016 to 2021 have been downloaded, but the data from 2000 to 2016 cannot be obtained. 
I just use:
dl.get("10-K", Name)

where the Name is a CIK of a company.

What is the reason for this? 
Thank you!

**Comment by scrappyreed** [comment]
Are you sure there are SEC filings for that CIK for that period?   Try a web query at this page:  

[https://www.sec.gov/edgar/search/?r=el#/dateRange=custom&category=custom&startdt=2001-01-01&enddt=2022-10-27]

If the web query doesn't return anything, the API won't either

**Comment by JJery-web** [comment]
> Are you sure there are SEC filings for that CIK for that period? Try a web query at this page:
> 
> [https://www.sec.gov/edgar/search/?r=el#/dateRange=custom&category=custom&startdt=2001-01-01&enddt=2022-10-27]
> 
> If the web query doesn't return anything, the API won't either

Thank you very much for your reply.

It's really strange. For example, the CIK is 0001350593. I downloaded the 2006-2021 10-K report through the sec-edgar-downloader. Based on your suggestion, I did not find any annual reports before 2006 through the search function[https://www.sec.gov/edgar/search/?r=el#/dateRange=custom&category=custom&startdt=2001-01-01&enddt=2022-10-27].

Is this because the SEC has not included it? Or did the company not disclose it? I don't know much about finance. I'm very eager to get your reply. Thank you!

**Comment by scrappyreed** [comment]
I suggest you read the documentation on the EDGAR website to understand what filings are available historically.

**Comment by JJery-web** [comment]
> I suggest you read the documentation on the EDGAR website to understand what filings are available historically.

Fine. Thank you. :(

**Comment by jadchaar** [comment]
Hi @JJery-web do take the suggestion of @scrappyreed, but also do check out v5.0 of this package which is a full re-write and should solve a lot of long-standing package issues. Please do let me know if this issue still persists. If you find the issue with incomplete downloads is still occurring please do re-open this issue or file a new one with details on the ticker and parameters used to help debug and reproduce the issue. Thanks!
