### ISSUE TITLE
Add support for official SEC requirements for API Access

### ISSUE THREAD

**Issue by rkeshwani** [jadchaar/sec-edgar-downloader#113]
Per the SEC documentation it looks like you need to add a header to every request to prevent being flagged as an Automated Tool.
Can support be added so that this can be implemented as a parameter? Currently randomized information is being added here. Which can be used if no parameter is provided but for those that want to do things the right way, this feature should be provided.

SEC Documentation:
https://www.sec.gov/os/webmaster-faq#code-support

<html>
<body>
<p style="box-sizing: border-box; margin: 0px 0px 10px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; line-height: 1.5; font-family: Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 13px; vertical-align: baseline; color: rgb(0, 0, 0); text-rendering: optimizelegibility; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Sample Declared Bot Request Headers:</p><div class="margin-left-20" style="box-sizing: border-box; margin: 0px 0px 1em 20px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Helvetica, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 13px; vertical-align: baseline; color: rgb(16, 31, 54); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

User-Agent: | Sample Company Name AdminContact@<sample company domain>.com
-- | --
Accept-Encoding: | gzip, deflate
Host: | www.sec.gov

</div>
</body>
</html>Sample Declared Bot Request Headers:

User-Agent:

Sample Company Name AdminContact@<sample company domain>.com

Accept-Encoding:

gzip, deflate

Host:

[www.sec.gov](http://www.sec.gov/)

**Comment by jadchaar** [comment]
Implemented in v5.0 - https://github.com/jadchaar/sec-edgar-downloader/releases/tag/5.0.0
