### ISSUE TITLE
N-PX file download issue

### ISSUE THREAD

**Issue by yimingsabrinazhang** [jadchaar/sec-edgar-downloader#115]
Hi everyone！

I am new to SEC EDGAR downloading procedure and come across an issue with downloading N-PX files. The only identifier is NPXfield (provided by the ISS database), which does not link to either CIK or Ticker. Any idea or comment on this issue is very appreciated. 

Thanks in advance for your help and suggestions!

**Comment by jadchaar** [comment]
I just verified that v5.0 of this package downloaded N-PX statements just fine. I validated with CIK `0000794105`:

```
from sec_edgar_downloader import Downloader

downloader = Downloader("foo", "bar@gmail.com")
downloaded = downloader.get("N-PX", "794105", limit=1)
print(downloaded)
```
