### ISSUE TITLE
Downloading file for searching by keywords

### ISSUE THREAD

**Issue by JennyHuang23** [jadchaar/sec-edgar-downloader#125]
Hi,
I try to download insider trading files by searching for CEOs. However, I cannot use "query" in the codes to search for keywords (see below). Does anyone know how to solve it?
![1694991962380](https://github.com/jadchaar/sec-edgar-downloader/assets/127916986/839e65bb-994c-4dbe-b168-a175bf71741c)

**Comment by jadchaar** [comment]
Hi @JennyHuang23 the ability to search via query was removed in v5.0. In v4 I was harnessing a private SEC Edgar API That I reverse engineered from this SEC Edgar full-text search website: https://www.sec.gov/edgar/search/. The private API was not stable and subject to breakage (as we saw a few months ago), so I decided to fully migrate to the public SEC Edgar API instead.
