### ISSUE TITLE
Error in URLs for certain accession_numbers

### ISSUE THREAD

**Issue by rthapliyal** [jadchaar/sec-edgar-downloader#126]
Check accession number: 0000950103-23-014290

Actual File Details URL (by clicking on the edgar website): 
https://www.sec.gov/Archives/edgar/data**/312070/**000095010323014290/dp200734_424b2-5333pps.htm

File_details_url from code: 
https://www.sec.gov/Archives/edgar/data**/31207/**000095010323014290/dp200734_424b2-5333pps.htm

You'll notice the truncated 0 at the end of that bolded folder above.
Let me know if you agree its a bug or if I'm doing something wrong here.

thx,
R

**Comment by rthapliyal** [comment]
The links were messed up in my trying to  bold the content causing issues.

Actual File Details URL (by clicking on the edgar website):
https://www.sec.gov/Archives/edgar/data312070/000095010323014290/dp200734_424b2-5333pps.htm

File_details_url from code:
https://www.sec.gov/Archives/edgar/data/31207/000095010323014290/dp200734_424b2-5333pps.htm

**Comment by VadarVillage** [comment]
First off, I love this package and your coding style is easy for me to follow.

the problem appears to be in _orchestrator.py, this line - change it to 'cik = cik.strip("0").lstrip(0)':
https://github.com/jadchaar/sec-edgar-downloader/blob/c1623363013ace56d675cdceca1846e7c3466b11/sec_edgar_downloader/_orchestrator.py#L110

**Comment by jadchaar** [comment]
Thank you @VadarVillage @rthapliyal for the report and kind words. I have raised a fix for this in a PR.

**Comment by jadchaar** [comment]
Hey folks, I just released v5.0.1 to address this: https://pypi.org/project/sec-edgar-downloader/
