### ISSUE TITLE
Pip install failure

### ISSUE THREAD

**Issue by haterade** [jadchaar/sec-edgar-downloader#25]
I'm having problems with the first step.  

The basic command "$ pip install -U sec-edgar-downloader"  does not work for me.

**Comment by jadchaar** [comment]
Hi @haterade, you should be able to install the tool by running the following command without the "$": `pip install -U sec-edgar-downloader`.

Hope this helps! Let me know if this does not work for you.

**Comment by haterade** [comment]
Unfortunately, no.   I tried this coding, which seemed to work for the install:

import pip._internal as pip
pip.main(['install', '-U sec-edgar-downloader'])
import sec_edgar_downloader
from sec_edgar_downloader import Downloader
dl = sec_edgar_downloader.Downloader()
dl.get_10k_filings("MSFT")


...but then I got the following message when I ran it.  
Usage:   
  t1.py install [options] <requirement specifier> [package-index-options] ...
  t1.py install [options] -r <requirements file> [package-index-options] ...
  t1.py install [options] [-e] <vcs project url> ...
  t1.py install [options] [-e] <local project path> ...
  t1.py install [options] <archive url/path> ...

no such option: -

**Comment by jadchaar** [comment]
That is peculiar. This seems to be an issue with pip.

What is the error output when you do `pip install -U sec-edgar-downloader`?

Mind trying `pip3 install -U sec-edgar-downloader` and `pip3 install sec-edgar-downloader`? This tool requires Python 3.6+ and you can check your version with `python3 --version`. Also maybe try upgrading pip with `pip3 install --upgrade pip`.

**Comment by haterade** [comment]
invalid syntax is the error I get for all of those.  I am version 3.8.

**Comment by jadchaar** [comment]
@haterade this is quite an odd issue. Mind providing with me with some more info so we can get to the bottom of this:

1. What OS are you using? If Windows, are you using WSL?
2. Does this happen when you pip install other packages like `requests` (e.g. `pip install -U requests`)?
3. Are you using a virtual environment?

Thanks.

**Comment by jadchaar** [comment]
Hi @haterade, I am closing this issue for now, but if it is still occurring, feel free to re-open it.
