### ISSUE TITLE
Form 4 (insider trading) 

### ISSUE THREAD

**Issue by flowtrader2016** [jadchaar/sec-edgar-downloader#35]
Hi,

Would it be difficult to retrieve "form 4" data with sec-edgar-downloader? 

Here is a recent [example](https://www.sec.gov/Archives/edgar/data/1067983/000120919120023268/0001209191-20-023268.txt):

[Wikipedia](https://en.wikipedia.org/wiki/Form_4) page

If this is not something you would look to implement do you have any suggestions around how I could modify sec-edgar-downloader to achieve this?

Thanks

**Comment by jadchaar** [comment]
Hey @flowtrader2016 thanks for asking! I have just added support for it and will be shipping v3.0.3 to PyPI very soon.
