### ISSUE TITLE
Form DEF 14A

### ISSUE THREAD

**Issue by meyerhj** [jadchaar/sec-edgar-downloader#39]
Hey, 

would it be difficult to include form DEF 14A (Proxy Statement) as a supported filing?

It contains a lot of useful information on shareholders and corporate governance which could be really useful.

https://en.wikipedia.org/wiki/Proxy_statement

Best wishes and thanks for the great tool!

**Comment by jadchaar** [comment]
Hey @meyerhj, thanks for the kind words. I have added support for DEF 14A filings in [v3.0.5](https://pypi.org/project/sec-edgar-downloader/). Check it out and let me know what you think!
