### ISSUE TITLE
Apply correct look & feel depending on a filing format

### ISSUE THREAD

**Issue by kuatroka** [jadchaar/sec-edgar-downloader#41]
There are multiple formats in EDGAR. For old filings it's all in `txt `format, but the new ones, are `xml `even thought original files on EDGAR are still `txt`. It means that all the recent filings are unreadable after download because they're all in `xml `format.

It would be great if this tool could distinguish between real `txt `file (old format) and the `xml `(new format) and apply appropriate formatting automatically. Maybe it can be done by searching the document for a string of characters **`/>`.** This would mean it's an .`xml `doc and if there isn't any, than it's a .`txt`. Maybe there is a certain year and a month starting from which all EDGAR filings started to be in the .`xml `format. 

Regards

**Comment by jadchaar** [comment]
Hey @kuatroka, thanks for bringing this up. SEC Edgar is kind of a wild west and lacks standardization (e.g. I am not sure if the start date of the new format was strictly enforced).

Can you give me two exact examples of filings that demonstrate the new and old format? That way I can put together a solution for this :).

**Comment by kuatroka** [comment]
I have a conceptual idea on how it might work:

Check [this page](https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001067983&type=13F-HR&dateb=&owner=exclude&count=100). 

If you filer it to view only documents prior the date **20000101**
and filter to only filings **13F-HR**
you will see only `.txt` files and if you open then them, you will find the file is an actual `.txt` with a clearly presented info and a table of all Berkshire's holdings.

Now, if you remove the filter on the date **20000101** and click on the `.txt `file, you will see a gibberish (`xml `formatted data), but if instead of the `.txt` file you open an `.html` file that contains word `*Table*` in its title, you will find a properly formatted table there

**Comment by jadchaar** [comment]
Interesting. It seems like older filings only post a txt file, but the newer ones have XML and HTML files in addition. I could potentially design a hierarchy that will attempt an XML parse if there is more than one submission file and if not, fall back to the txt.

Do you know if this is the case with other filing types as well?

**Comment by kuatroka** [comment]
I check all the filing types and here is the logic:

- All filings, new or old have at least a `.txt` file
- Starting from certain year some filings appear in other formats in addition to the always present `.txt`  format.
-  If there is only a `.txt` file, then it's formatted in a normal way, but if besides the `.txt` there are other formats, then the `.txt` file is formatted as an `xml `and not easily readable.
- Other than the `.txt`, other main formats are: `.xml` and `.htm` or `.html`
- To identify if there are other formats other than .`txt` the flow is:

   1. Parse the .txt and search for the tag `<FILENAME>
   2. If it exists, what comes after the `>` tag is the file name we are interested in. Capture it in a 
       variable `A`.
   3. Capture the current url and change it by swapping whatever is there after the last `/` for the 
      variable `A` as in the gif below.
![sec2](https://user-images.githubusercontent.com/9093546/83462904-4f291a00-a464-11ea-9418-dd98157811b0.gif)

**Comment by jadchaar** [comment]
Is the HTML file more easily parsable than the TXT file since it is technically XML?

**Comment by kuatroka** [comment]
Not really sure. My idea was to have it in such an easy format so it can easily be opened with pandas for further analysis and such. I know pandas has simple `.csv` and` .html` read commands. Also `.html` seems to be of a smaller size, but in reality, it's up to you as I bet you know better what is easier to parse.

**Comment by jadchaar** [comment]
As part of v4 of this package (https://github.com/jadchaar/sec-edgar-downloader/pull/52), I am adding the ability to download filing details provided by the EDGAR Search API (HTML or XML file depending on the filing type). That said, the XML file provided by the API is not the one you are looking for, so I will need to expand my search for a solution here. A potential idea I have is to take the accession number and append `-index.html` to get the index of all downloadable files like in your GIFs: https://www.sec.gov/Archives/edgar/data/0000102909/000110465920125446/0001104659-20-125446-index.html. Then, I will need to obtain this webpage and scrape/parse out all of the document hyperlinks for downloading. This will most likely come in a future release, but I have laid the groundwork in v4.

**Comment by ake3210** [comment]
Thank you for this package, it helps a lot! Unfortunately, I am currently facing the same problem as kuatroka (the author of this issue). Is there already an update regarding his question? 

If the package would allow for receiving the readable .txt and later on .html-files, is it possible to include a code that automatically takes the .html-files from the folder where it has been stored and convert it into a .txt-file? As a newbie to Python and Github, I solely found this option which might help to incorporate it into the package.

from bs4 import BeautifulSoup
soup = BeautifulSoup(html)
print(soup.get_text())

source: https://stackoverflow.com/questions/14694482/converting-html-to-text-with-python

Thank you so much for your effort to improve the package!

**Comment by jadchaar** [comment]
Sorry for the delayed response to this request--things have been hectic recently. I am going to keep the issue open so I can give it another look going forward and see what I can do!

**Comment by jadchaar** [comment]
I looked into this a bit and it seems like an involved web scraping approach is required since the `FILENAME` attribute inside of the full submission does not seem sufficient to locate the table files. Take this one for example: https://www.sec.gov/Archives/edgar/data/1067983/000095012321015518/0000950123-21-015518-index.html. Here the filename is listed as `<FILENAME>6820.xml`, but the file is located at https://www.sec.gov/Archives/edgar/data/1067983/000095012321015518/0000950123-21-015518-6820.xml. This inconsistency makes it hard to generalize the URL without scraping the index page for the accession number. I am trying to avoid scraping at all costs since it is fragile. In v5, I am adopting the official Edgar API which should improve the quality of the downloaded documents, especially XML documents.

Thanks for elaborating on your solution. I hope others find it helpful. I am going to close this issue as I am not sure there is much I can do without adding scraping to the index file for the accession number. Also, the XML is available in the full submission TXT file as you stated, so it can be parsed out if needed.

Thanks again!
