### ISSUE TITLE
Add Form 6-K to Filing Type

### ISSUE THREAD

**Issue by jasontwright** [jadchaar/sec-edgar-downloader#47]
When a non-U.S. issuer files an annual, semi-annual, or quarterly financial report with the regulators in its home country, it must submit a cover statement on the foreign filings to the SEC, which relieves the burden of dual reporting for certain non-U.S. issuers who must file under these rules. In essence, this supplements the 20-F, which you have already included in the filing type.  

Since any information that a foreign company issues to its local securities regulators, investors or stock exchange must also be submitted on the Form 6-K, the 6-K is a catchall for material information that arises in between annual and quarterly financial reports, which are also submitted to the SEC.

Information is considered material to a foreign private issuer if it involves a change in business, change in management or control, material changes in the outstanding number of securities, change in accountants, changes in securities, bankruptcy or receivership, material legal proceedings, etc.

**Comment by jadchaar** [comment]
This should also make its way to the revamped v4 update I am working towards :).
