### ISSUE TITLE
Add ability to download amended SEC filings

### ISSUE THREAD

**Issue by jkconaway** [jadchaar/sec-edgar-downloader#50]
Hi! Many companies have to amend and resubmit their filings for one reason or another, so it would be nice if you could add to the list of supported filings the amended versions of each. For example, 10-K/A, 13F-HD/A, etc.

**Comment by jadchaar** [comment]
Thanks for the suggestion @jkconaway! As of now, amends can be downloaded for all filings that support them by passing the  `include_amends=True` kwarg to the `dl.get()` function, but I agree this can be better documented.

**Comment by jkconaway** [comment]
Oh, excellent! I missed that info in the "Example Usage". Thank you for your quick reply!

**Comment by jadchaar** [comment]
No problem! I will make this more clear in the documentation :).
