### ISSUE TITLE
SSL error 

### ISSUE THREAD

**Issue by emjc93** [jadchaar/sec-edgar-downloader#63]
Hi, I am currently getting the error on python version 3.7 :

Example input:

dl.get("8-K", "AAPL", amount=1)

error:

SSLError: HTTPSConnectionPool(host='efts.sec.gov', port=443): Max retries exceeded with url: /LATEST/search-index (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

happens with request and can be avoided by  changing r = requests.get('https://api.github.com/user') to  vertify = False. r = requests.get('https://api.github.com/user', verify=False).

Thanks

**Comment by jadchaar** [comment]
Hi @emjc93, I am unable to reproduce this on my end:

```python
env ❯ python3
Python 3.9.2 (default, Feb 19 2021, 17:43:04)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sec_edgar_downloader import Downloader
>>> dl = Downloader()
>>> dl.get("8-K", "AAPL", amount=1)
1
```

**Comment by emjc93** [comment]
Hi jadchaar - thanks so much for coming back to me.
Ah ok -  I will look into it further.

**Comment by jadchaar** [comment]
Feel free to re-open this if you are able to reproduce the problem :)!
