### ISSUE TITLE
Adding new filing types

### ISSUE THREAD

**Issue by bosanipietro** [jadchaar/sec-edgar-downloader#66]
Thank you very much for the work you have contributed!
I would like to ask whether it would be possible to add S-1/A filings to the list of potential filings that can be downloaded.

**Comment by jadchaar** [comment]
Hi @bosanipietro, this is actually currently possible with the following command: `dl.get("S-1", "0001477333", include_amends=True)`

Here is an example of the command run for Cloudflare (CIK: 0001477333) which has an S-1 and two S-1/A forms:
![Screen Shot 2021-03-31 at 5 01 24 PM](https://user-images.githubusercontent.com/7388203/113210868-bc533a80-9242-11eb-89d4-542dfa0bbae3.png)
