### ISSUE TITLE
403 Client Error

### ISSUE THREAD

**Issue by samuel6269** [jadchaar/sec-edgar-downloader#68]
Hi, I was trying to execute the following:

'dl.get('10-Q', '0000066740', after='2018-01-01')'

But I got a few error messages regarding a 403 client error. Here's an example of one: 
'Skipping filing detail download for '0001558370-20-011804' due to network error: 403 Client Error: Forbidden for url: https://www.sec.gov/Archives/edgar/data/0000066740/000155837020011804/mmm-20200930x10q.htm.'

Would this have to do with possibly my IP address getting blocked?

**Comment by jadchaar** [comment]
Hi @samuel6269, does this happen on any filing download (e.g. what if you try downloading a single 8-K or 10-K right now?).

Also, did this happen after a bunch of downloads or on your first one? Rate-limiting has always been a cloudy area with the SEC, so I am always looking to improve it.

**Comment by jkconaway** [comment]
Hello! I am receiving the same error message. I am attempting to download 13F-HD for a list of CIKs; it is skipping a handful of filings for each CIK.

For example, focusing on only one ticker, I just collected ten 13F-HR filings and skipped three with the following:
dl.get("13F-HR", "BABA", after="2018-01-01", download_details=False, include_amends=True)

If I change after="2018-01-01" to amount=1 it works, but only if I wait some seconds (not sure of the exact number) in between requests.

**Comment by samuel6269** [comment]
@jadchaar, I tried just downloading a single 10-Q statement for any company, and the result is pretty random. Some runs it was able to download, while other runs, I got this same error. 

I was able to download multiple statements during my first week of use without any errors. (I downloaded 10-Q statements for about 20 companies during a 4 year time span). However, when I try to now download any single statement for any company (including companies I used earlier) it gives me this error on some runs.
 
For now, I can modify my routine to have dl.get() download one statement at a time, with an added wait time in between. Thank you for looking into this!

**Comment by schawnlee** [comment]
Hi dear @jadchaar, I am facing with the same issue trying to download all the 10-K fillings from SP500 firms in the last 10 years. It worked just fine last month but now it returns 403 error. I can however, access the files through the URL with my browser.  If the access restriction comes from the SEC side, a solution maybe to collect the undownloadable paths and try to re-access them.

Greetings

**Comment by jadchaar** [comment]
> Hello! I am receiving the same error message. I am attempting to download 13F-HD for a list of CIKs; it is skipping a handful of filings for each CIK.
> 
> For example, focusing on only one ticker, I just collected ten 13F-HR filings and skipped three with the following:
> dl.get("13F-HR", "BABA", after="2018-01-01", download_details=False, include_amends=True)
> 
> If I change after="2018-01-01" to amount=1 it works, but only if I wait some seconds (not sure of the exact number) in between requests.

Thank you everyone for your input, this is very odd. Running `dl.get("13F-HR", "BABA", after="2018-01-01", download_details=False, include_amends=True)` like @jkconaway mentioned returns me the same errors (sometimes 2 or sometimes 3 depending on the run), despite the URL working properly in the browser. This makes me think that the SEC is attempting to block automated crawlers that do not have a user-agent string in the request headers.

I was able to fix this by generating a fake, random user-agent string using [Faker](https://github.com/joke2k/faker/). This now reliably downloads filings without this error :). Going to publish a new release with the fixes soon!

**Comment by jadchaar** [comment]
Once version 4.0.3 is released to PyPi, would ya'll mind giving this another go to see if it has been resolved? Thanks :).

**Comment by jadchaar** [comment]
Version 4.0.3 has been published, please give it another shot :)!

**Comment by jkconaway** [comment]
> Version 4.0.3 has been published, please give it another shot :)!

@jadchaar I am currently pulling 13F-HD filings for a list of 3,000+ CIKs and it is working without any issues! Thank you for being so prompt at resolving this!
