### ISSUE TITLE
preventing 403 client error

### ISSUE THREAD

**Issue by knslee07** [jadchaar/sec-edgar-downloader#70]
Hello,

First, I would thank you for making this Python module. 
I have been trying to download SEC filings and realized that since SEC.gov does not allow making more than ten requests at the same time, when not setting up the amount option, I find 403 client errors like this

Skipping full submission download for '0001018724-19-000004' due to network error: 403 Client Error: Forbidden for url: https://www.sec.gov/Archives/edgar/data/0001018724/000101872419000004/0001018724-19-000004.txt.
Skipping full submission download for '0001018724-15-000006' due to network error: 403 Client Error: Forbidden for url: https://www.sec.gov/Archives/edgar/data/0001018724/000101872415000006/0001018724-15-000006.txt.
Skipping full submission download for '0001193125-13-028520' due to network error: 403 Client Error: Forbidden for url: https://www.sec.gov/Archives/edgar/data/0001018724/000119312513028520/0001193125-13-028520.txt.
Skipping full submission download for '0001193125-12-032846' due to network error: 403 Client Error: Forbidden for url: https://www.sec.gov/Archives/edgar/data/0001018724/000119312512032846/0001193125-12-032846.txt.

It would be super awesome to send ten request at a time to the API with loops when executing dl.get(). Or, let me know if there is already a workaround for this. Thank you.

**Comment by jadchaar** [comment]
Hi @knslee07, what version of this package are you using? You can find out as follows:

```shell
env ❯ python3
Python 3.9.2 (default, Mar 26 2021, 23:22:38)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sec_edgar_downloader
>>> sec_edgar_downloader.__version__
'4.0.3'
```

**Comment by knslee07** [comment]
Thank you for your reply.
Mine is 4.0.2. After reading your reply, I just updated it to 4.0.3. Will that solve the issue? I have written a code using time.sleep(). It did reduce the number of the messages but did not completely solve the issue. 
After updating, I have been test-running my code and so far have not seen the same message. Is this thanks to the update for the newest version? Anyway, if that is what is intended, this 4.0.3 update really save the day for me.

**Comment by jadchaar** [comment]
Yup I recently pushed out v4.0.3 since a lot of users were complaining about the 403 errors. It seems like the SEC has gotten stricter about their rate limiting recently, so I needed to generate a fake user-agent on each request to make it seem like the requests are coming from a browser rather than a script. This seems to have alleviated most of the 403 errors :). I am already sleeping every .10s in the package code to align with the SEC rate-limiting rules, but it seems like the user-agent thing is also necessary :). Feel free to re-open if this comes up again.
