### ISSUE TITLE
403 Client error

### ISSUE THREAD

**Issue by tczhaodachuan** [jadchaar/sec-edgar-downloader#71]
Hi:
We've been using the package 3.0.5 version, it was working fine. However, recently it starts to throw this error:

File "/aitrading/etl/edgar/sec_filing.py", line 53, in get_data
    after_date=self.after_yyyymmdd, before_date=self.before_yyyymmdd)
  File "/usr/local/lib/python3.7/site-packages/sec_edgar_downloader/Downloader.py", line 153, in get
    include_amends,
  File "/usr/local/lib/python3.7/site-packages/sec_edgar_downloader/_utils.py", line 76, in get_filing_urls_to_download
    resp.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&owner=exclude&start=0&count=100&CIK=1336528&type=13F-HR&dateb=20210412&output=atom

I suspect it's because the `header` doesn't pass in as the browser, is that true?

**Comment by tczhaodachuan** [comment]
I am searching online document, it could be related with https://developer.edgar-online.com/docs/RateLimits

**Comment by jadchaar** [comment]
Hi @tczhaodachuan, sadly I am no long maintaining the 3.x branch of this package. Try upgrading to version 4.0.3 by running `pip install -U sec-edgar-downloader`. My most recent update added randomized `user-agent` headers to requests to prevent rate limiting in addition to the 10 requests per second (I `time.sleep(.10)` in the code) required by the SEC (https://www.sec.gov/os/accessing-edgar-data).

**Comment by tczhaodachuan** [comment]
Yes, I added a sleep method to avoid this problem. I will close this issue for now and update my versions.
