### ISSUE TITLE
Is it possible to download all the file for particular filling type ex. N-PORT for a given date?

### ISSUE THREAD

**Issue by yogeshdesh17** [jadchaar/sec-edgar-downloader#73]
thanks for such an amazing python package!

Is it possible to download all the file for particular filling type ex. N-PORT for a given date? i mean without passing "ticker_or_cik" parameter.

**Comment by jadchaar** [comment]
Closing in favor of https://github.com/jadchaar/sec-edgar-downloader/issues/42. Currently, this is not supported in sec-edgar-downloader, but I will look into adding it in a future release. In the meantime, check out https://pypi.org/project/python-edgar/, it might be able to fill this gap for you!
