### ISSUE TITLE
ticker greedy search

### ISSUE THREAD

**Issue by knslee07** [jadchaar/sec-edgar-downloader#75]
Hello,

I have been enjoying this module. I found that when specifying a firm with a ticker, the code downloads other firms that include that ticker. For instance, when I use "DE", the computer downloads files from tens of CIKs. So are other short tickers like "V". Can you revise your source code so that it exactly finds only that ticker, not every ticker that includes the search word?

**Comment by jadchaar** [comment]
Closing this issue for now, but please let me know if something else comes up :)!

**Comment by jadchaar** [comment]
No problem at all! The SEC Edgar full text search system (which is quite new) is a bit whack, and I really do not understand why it treats tickers as partial searches rather than a single identifier. I wish there were more granularity to the system, but sadly this is what we are stuck with :(.
