### ISSUE TITLE
Unable to navigate within the file

### ISSUE THREAD

**Issue by yyang6** [jadchaar/sec-edgar-downloader#79]
When I click on the web links from the downloaded html files, the links don't actually navigate within the file, but direct to other web pages. For example, https://www.sec.gov/Archives/edgar/data/0000092116/000105690321000021/#i61d362493b964e1b9b072fa4670bd2f3_7

**Comment by jadchaar** [comment]
Hi @yyang6 apologies for the late response, things have been hectic on my end. Thanks for reporting this, I will look into it :).
