### ISSUE TITLE
TreeBuilderForHtml5lib

### ISSUE THREAD

**Issue by TZimm55** [jadchaar/sec-edgar-downloader#81]
Code used (I just copied from your instructions, but replaced the downloader location):
```
from sec_edgar_downloader import Downloader

# Initialize a downloader instance. If no argument is passed
# to the constructor, the package will download filings to
# the current working directory.
dl = Downloader(r"C:\Users\[User Name]\Downloads\SEC Files")

# Get all 8-K filings for Apple (ticker: AAPL)
dl.get("8-K", "AAPL")
```

This is the error that I am getting:
`class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'`

My inexperience coding research found the following, [LINK](https://github.com/Sigil-Ebook/Sigil/issues/316#issuecomment-331662556).
I am referencing windonsky who commented on 2017.09.23. 

My apologies if I did something wrong when trying to run this.

**Comment by jadchaar** [comment]
Hi @TZimm55, this seems to be due to beauitfulsoup (the parsing engine used by this package) falling back to html5lib rather than using lxml. Try doing the following in a shell:

```shell
python3 -m venv env
source env/bin/activate
pip install -U sec-edgar-downloader
```

Then try running the script you included above. If that does not work, can you tell me the output of `pip list` inside the virtual env?

**Comment by TZimm55** [comment]
Hopefully this is helpful, I am pretty new to using the terminal/programming.

![image](https://user-images.githubusercontent.com/77949097/123962983-a48d6e80-d977-11eb-8a8b-6fd9608efdef.png)

**Comment by jadchaar** [comment]
Hi @TZimm55, you need to activate your virtual environment after creating it by doing `source env/bin/activate`. When I do `pip list` on my end, I get the following:

```shell
~/Downloads
env ❯ pip list
Package              Version
-------------------- ---------
beautifulsoup4       4.9.3
bs4                  0.0.1
certifi              2021.5.30
chardet              4.0.0
Faker                8.8.2
idna                 2.10
lxml                 4.6.3
pip                  21.1.1
python-dateutil      2.8.1
requests             2.25.1
sec-edgar-downloader 4.2.1
setuptools           56.0.0
six                  1.16.0
soupsieve            2.2.1
text-unidecode       1.3
urllib3              1.26.6
```

Notice how I do not have html5lib, so bs4 is forced to use lxml instead.

**Comment by TZimm55** [comment]
@jadchaar I can't get it to work and I don't want to waste your time. We can just close this issue since its a user error. I appreciate the responses.

**Comment by jadchaar** [comment]
> @jadchaar I can't get it to work and I don't want to waste your time. We can just close this issue since its a user error. I appreciate the responses.

You are not wasting my time :). I would love to get this working for you. Try this final option of uninstalling html5lib: `pip uninstall html5lib`.

**Comment by TZimm55** [comment]
@jadchaar that did the trick! 

My whole goal was to be able to get a printed version of the filing, and the for life of me I could not find a way to do that via the SEC's website.

I opened the .html file once it downloaded.
![image](https://user-images.githubusercontent.com/77949097/124010317-4cb92c80-d9a4-11eb-9b11-44300e5dc273.png)

Thank you for your help and good job on the program, very nice!

**Comment by jadchaar** [comment]
Fantastic glad that worked :)! Best of luck going forward!
