### ISSUE TITLE
Getting data with CIK does not work

### ISSUE THREAD

**Issue by janfe2o3** [jadchaar/sec-edgar-downloader#84]
Hi really good work you're doing here, already helped me a lot! However, while it works fine with tickers, the download of fillings via CIK does not work for me. I would be very happy if you could fix this!

Example Microsoft:
![image](https://user-images.githubusercontent.com/85082017/124638503-5272ae80-de8b-11eb-865c-617cc9a78f0a.png)

**Comment by jadchaar** [comment]
Hi @janfe2o3, I will have to investigate this in more detail once I am back home, but I just tried this and it worked:

```python
>>>dl.get("10-K", "0000789019", amount=1)
1
```

I gotta look into why the truncated CIK is causing trouble because I am able to reproduce the bug you are seeing.
