### ISSUE TITLE
Search key word that are a phrase

### ISSUE THREAD

**Issue by Jennyyanhuadong** [jadchaar/sec-edgar-downloader#87]
# Get all Apple proxy statements that contain the term "contract design", I use the code:
dl.get("DEF 14A", "AAPL", query="contract design")

However, the downloaded files include 'contract' or 'design', but not include the exact phrase 'contract design'.

**Comment by jadchaar** [comment]
Hi @Jennyyanhuadong, can you try including quotes around your query like: `dl.get("DEF 14A", "AAPL", query="'contract design'")` or `dl.get("DEF 14A", "AAPL", query="\"contract design\"")`? That should search for the entire phrase.

**Comment by Jennyyanhuadong** [comment]
Hi @jadchaar, thanks a lot for your reply. dl.get("DEF 14A", "AAPL", query="'contract design'") does now work, but dl.get("DEF 14A", "AAPL", query="\"contract design\"") works.
