### ISSUE TITLE
Change User Agent

### ISSUE THREAD

**Issue by RainmakerP** [jadchaar/sec-edgar-downloader#94]
Hello,

The code is constantly breaking down. We've tried different IPs but it's not working. It's possibly because the entire library and all its users are using one, common, user agent.

So, how do we change the user agent?

Regards,

**Comment by jadchaar** [comment]
Hi @RainmakerP, what type of errors/status codes are you receiving? Also, are you using this library across multiple threads or processes?

Currently, I randomize the User-Agent string automatically on each request: https://github.com/jadchaar/sec-edgar-downloader/blob/4a42cf82f086d0e262ea1b2a0e4a02d6047d4d20/sec_edgar_downloader/_utils.py#L248

**Comment by jadchaar** [comment]
Feel free to reopen this issue if you have any further comments or concerns :)!
