### ISSUE TITLE
Add a check to prevent re-downloading files already downloaded

### ISSUE THREAD

**Issue by donbowen** [jadchaar/sec-edgar-downloader#97]
A feature/enhancement request. 

I think this could be implemented in the main [downloader class](https://github.com/jadchaar/sec-edgar-downloader/blob/master/sec_edgar_downloader/Downloader.py) by inserting at line 182 a check that removes anything in the `filings_to_fetch` that is already downloaded.

**Comment by JJery-web** [comment]
How to use this function please? Due to the fact that it usually stops by 404

**Comment by jadchaar** [comment]
Hi all, I have been hard at work re-writing this package from the ground up to use the SEC's new, official Edgar API. This has been implemented as part of v5.0. Check out the new release and let me know what you think!
