### ISSUE TITLE
404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by xueying-bi** [jadchaar/sec-edgar-downloader#99]
I am trying to use a list of cik to download "NSAR-A" filling.  Here is the code I use:

```
for i in range(0,len(cik)-1):
    dl.get("NSAR-A", cik[i], after="2000-01-01", before="2018-12-31")
    print("Now Downloading"+ str(i))
```

However, sometimes here is a message shown that: "Skipping filing detail download for 'xxx' due to network error: 404 Client Error: Not Found for url: xxx". I am not sure about reason behind, does it mean I cannot download these files or these files do not exist?

Thank you for your help!

**Comment by lixuanze** [comment]
I am facing the same issue

**Comment by lixuanze** [comment]
Is the issue got fixed? If so, how does it got fixed?

**Comment by lpyleo-123** [comment]
Hello! I am facing the same 404 problem today.

**Comment by DarrenForsythe** [comment]
Appears that the SEC is blocking the `user-agent` that is faker is making.

You can patch out the method fairly easily and the functionality should be, 

```
def static_user_agent() -> str:
    return 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'


sec_edgar_downloader._utils.generate_random_user_agent = static_user_agent

**Comment by jadchaar** [comment]
@DarrenForsythe that is interesting because the SEC explicitly asks the user-agent to be declared as `Sample Company Name AdminContact@<sample company domain>.com` according to https://www.sec.gov/os/webmaster-faq#code-support

I wonder if using domain names like gmail.com, hotmail.com etc are getting throttled harder than company domains.

**Comment by jadchaar** [comment]
Hi all, please do try using v5.0 of this package that was released today and do let me know if the issue still occurs. v5.0 allows you to now pass a company name and email address which I use to form the user-agent to conform to the SEC's fair access policy. This should prevent any 4xx errors from occurring (e.g. 429 throttles) unless there is a legitimate issue at play (e.g. the filing is not available). Please do re-open this issue if the problem re-occurs with v5.
